# STAGE 1

FROM node:20-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps 

COPY . .

RUN npm run build -- --configuration production

# STAGE 2

FROM nginx:alpine

COPY --from=builder /app/dist/TodoList.WEB/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
